# Generated by Django 5.1.6 on 2026-03-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_appversion_id_alter_article_id_alter_book_id_and_more'),
        ('paper_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificpaper',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_paper', to='application.article'),
        ),
        migrations.AddField(
            model_name='scientificpaper',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scientificpaper',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
