# Generated by Django 5.1.6 on 2026-03-21 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_builder', '0002_scientificpaper_article_scientificpaper_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificpaper',
            name='branding_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scientificpaper',
            name='branding_label',
            field=models.CharField(blank=True, default='Powered by MathSphere Writer', max_length=160),
        ),
        migrations.AddField(
            model_name='scientificpaper',
            name='document_kind',
            field=models.CharField(choices=[('paper', 'Paper'), ('book', 'Book'), ('report', 'Report')], default='paper', max_length=50),
        ),
        migrations.CreateModel(
            name='ScientificPaperSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('frontmatter', 'Frontmatter'), ('chapter', 'Chapter'), ('section', 'Section'), ('appendix', 'Appendix'), ('references', 'References')], default='section', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='paper_builder.scientificpaper')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('paper', 'slug'), name='unique_paper_section_slug')],
            },
        ),
    ]
