# Generated by Django 5.1.6 on 2026-03-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_builder', '0003_scientificpaper_branding_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificpapersection',
            name='progress_state',
            field=models.CharField(choices=[('todo', 'Todo'), ('drafting', 'Drafting'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
