INTEGRAL_METHODS = {
    "auto": {
        "label": "Auto researcher route",
        "family": "hybrid",
        "engine": "sympy",
        "summary": "Expression diagnostics decide the symbolic-first route and decimal confirmation.",
        "numeric_strategy": "sympy.N(definite_value, 15)",
        "adapter_status": "active",
    },
    "symbolic": {
        "label": "SymPy symbolic integrate",
        "family": "analytic",
        "engine": "sympy",
        "summary": "Closed-form primitive or exact definite value is attempted with SymPy integrate.",
        "numeric_strategy": "sympy.N(definite_value, 15)",
        "adapter_status": "active",
    },
    "risch-heurisch": {
        "label": "Risch/heurisch route",
        "family": "analytic",
        "engine": "sympy",
        "summary": "Records a Risch/heurisch-style symbolic intent for elementary antiderivative search.",
        "numeric_strategy": "sympy.integrate with reproducibility metadata",
        "adapter_status": "code-ready",
    },
    "substitution": {
        "label": "Substitution",
        "family": "analytic",
        "engine": "sympy/manual",
        "summary": "u-substitution intent is recorded for chain-rule style integrals.",
        "numeric_strategy": "symbolic route with derivative/back-substitution check",
        "adapter_status": "code-ready",
    },
    "integration-by-parts": {
        "label": "Integration by parts",
        "family": "analytic",
        "engine": "sympy/manual",
        "summary": "Integration-by-parts intent is recorded for product integrals.",
        "numeric_strategy": "symbolic route with boundary-term verification",
        "adapter_status": "code-ready",
    },
    "partial-fractions": {
        "label": "Partial fractions",
        "family": "analytic",
        "engine": "sympy",
        "summary": "Partial-fraction decomposition intent is recorded for rational integrals.",
        "numeric_strategy": "symbolic route with apart reconstruction check",
        "adapter_status": "code-ready",
    },
    "trig-substitution": {
        "label": "Trigonometric substitution",
        "family": "analytic",
        "engine": "sympy/manual",
        "summary": "Trigonometric substitution intent is recorded for radical quadratic patterns.",
        "numeric_strategy": "symbolic route with branch/domain verification",
        "adapter_status": "code-ready",
    },
    "numeric-check": {
        "label": "Exact value numeric check",
        "family": "numeric",
        "engine": "sympy",
        "summary": "The exact definite result is evaluated as a decimal for verification.",
        "numeric_strategy": "sympy.N(definite_value, 15)",
        "adapter_status": "active",
    },
    "adaptive-quadrature": {
        "label": "Adaptive quadrature",
        "family": "numeric",
        "engine": "scipy/mpmath",
        "summary": "Adaptive subdivision quadrature is the selected numeric strategy for smooth finite intervals.",
        "numeric_strategy": "planned: scipy.integrate.quad or mpmath.quad with absolute/relative tolerance",
        "adapter_status": "code-ready",
    },
    "gauss-legendre": {
        "label": "Gauss-Legendre quadrature",
        "family": "numeric",
        "engine": "numpy/scipy",
        "summary": "Fixed-order Gaussian quadrature is selected for smooth finite-interval integrals.",
        "numeric_strategy": "planned: numpy.polynomial.legendre.leggauss(order)",
        "adapter_status": "code-ready",
    },
    "composite-simpson": {
        "label": "Composite Simpson",
        "family": "numeric",
        "engine": "scipy",
        "summary": "Uniform-grid Simpson integration is selected for sampled data and sensitivity sweeps.",
        "numeric_strategy": "planned: scipy.integrate.simpson over sampled grid",
        "adapter_status": "code-ready",
    },
    "tanh-sinh": {
        "label": "Tanh-sinh quadrature",
        "family": "numeric",
        "engine": "mpmath",
        "summary": "Double-exponential quadrature is selected for endpoint singularity or high-precision cases.",
        "numeric_strategy": "planned: mpmath.quad with tanh-sinh style high precision",
        "adapter_status": "code-ready",
    },
    "monte-carlo": {
        "label": "Monte Carlo integration",
        "family": "numeric",
        "engine": "numpy",
        "summary": "Sampling-based integration is selected for high-dimensional or complex-domain problems.",
        "numeric_strategy": "planned: seeded sampling with confidence interval",
        "adapter_status": "planned",
    },
    "residue-contour": {
        "label": "Residue/contour method",
        "family": "analytic",
        "engine": "sympy/manual",
        "summary": "Complex-analysis residue method is selected for contour integral candidates.",
        "numeric_strategy": "not numeric; requires contour and pole assumptions",
        "adapter_status": "planned",
    },
    "series-expansion-integral": {
        "label": "Series expansion integral",
        "family": "hybrid",
        "engine": "sympy",
        "summary": "Series expansion and term-by-term integration intent is recorded.",
        "numeric_strategy": "planned: series truncation with remainder/numeric comparison",
        "adapter_status": "code-ready",
    },
    "special-functions": {
        "label": "Special functions",
        "family": "analytic",
        "engine": "sympy",
        "summary": "Special-function closed form intent is recorded when elementary form is not available.",
        "numeric_strategy": "symbolic special-function route with numeric validation",
        "adapter_status": "code-ready",
    },
}

INTEGRAL_METHOD_CHOICES = tuple((method_id, meta["label"]) for method_id, meta in INTEGRAL_METHODS.items())


def get_integral_method(method_id: str | None) -> tuple[str, dict[str, str]]:
    normalized = method_id if method_id in INTEGRAL_METHODS else "auto"
    return normalized, INTEGRAL_METHODS[normalized]
