# Generated by Django 5.1.6 on 2026-03-18 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0006_alter_appversion_id_alter_article_id_alter_book_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('matrix', 'Matrix'), ('integral', 'Integral'), ('differential', 'Differential'), ('analysis', 'Analysis'), ('geometry', 'Geometry'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('icon_name', models.CharField(default='FlaskConical', max_length=64)),
                ('accent_color', models.CharField(default='blue', max_length=32)),
                ('computation_mode', models.CharField(choices=[('client', 'Client'), ('hybrid', 'Hybrid'), ('server', 'Server')], default='client', max_length=16)),
                ('estimated_minutes', models.PositiveIntegerField(default=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratory_modules', to='application.project')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
