# Generated by Django 5.1.6 on 2026-03-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_add_notebook_studio_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorymodule',
            name='project',
        ),
    ]
