import { SCIENTIFIC_OBJECT_SCHEMA_VERSION, type EcosystemAppId, type ScientificArtifact, type ScientificObject, type ScientificObjectKind, type ScientificObjectReference, type ScientificObjectRevision, type ScientificProvenance } from "./contracts";

const DB_NAME = "axion-science-local-v1";
const DB_VERSION = 1;
const OBJECTS_STORE = "objects";
const REVISIONS_STORE = "revisions";
const REFERENCES_STORE = "references";
interface StoredRevision<TPayload = unknown> extends ScientificObjectRevision<TPayload> { key: string; }
export interface StoredScientificReference { id: string; projectId: string; containerObjectId?: string; role?: string; reference: ScientificObjectReference; createdAt: string; }

function makeId() { if (typeof crypto !== "undefined" && "randomUUID" in crypto) return crypto.randomUUID(); return `local-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`; }
function requireIndexedDb() { if (typeof indexedDB === "undefined") throw new Error("LOCAL_OBJECT_STORE_UNAVAILABLE"); }
function requestResult<T>(request: IDBRequest<T>): Promise<T> { return new Promise((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error || new Error("INDEXEDDB_REQUEST_FAILED")); }); }
function transactionDone(transaction: IDBTransaction): Promise<void> { return new Promise((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onabort = () => reject(transaction.error || new Error("INDEXEDDB_TRANSACTION_ABORTED")); transaction.onerror = () => reject(transaction.error || new Error("INDEXEDDB_TRANSACTION_FAILED")); }); }
async function openDatabase(): Promise<IDBDatabase> { requireIndexedDb(); return await new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, DB_VERSION); request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains(OBJECTS_STORE)) { const store = db.createObjectStore(OBJECTS_STORE, { keyPath: "id" }); store.createIndex("byProject", "projectId", { unique: false }); store.createIndex("byKind", "kind", { unique: false }); } if (!db.objectStoreNames.contains(REVISIONS_STORE)) { const store = db.createObjectStore(REVISIONS_STORE, { keyPath: "key" }); store.createIndex("byObject", "objectId", { unique: false }); } if (!db.objectStoreNames.contains(REFERENCES_STORE)) { const store = db.createObjectStore(REFERENCES_STORE, { keyPath: "id" }); store.createIndex("byProject", "projectId", { unique: false }); store.createIndex("byReferencedObject", "reference.objectId", { unique: false }); } }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error || new Error("INDEXEDDB_OPEN_FAILED")); }); }
function revisionKey(objectId: string, revision: number) { return `${objectId}:${revision}`; }

export async function createLocalScientificObject<TPayload>(input: { projectId: string; kind: ScientificObjectKind; domain?: string; title: string; sourceApp: EcosystemAppId; payload: TPayload; provenance: ScientificProvenance; metadata?: Record<string, unknown>; artifacts?: ScientificArtifact[]; }): Promise<ScientificObject<TPayload>> { const db = await openDatabase(); const id = makeId(); const now = new Date().toISOString(); const revision: ScientificObjectRevision<TPayload> = { objectId: id, revision: 1, payload: input.payload, provenance: input.provenance, artifacts: input.artifacts, createdAt: now }; const object: ScientificObject<TPayload> = { id, projectId: input.projectId, kind: input.kind, domain: input.domain, schemaVersion: SCIENTIFIC_OBJECT_SCHEMA_VERSION, title: input.title, sourceApp: input.sourceApp, currentRevision: 1, metadata: input.metadata, revision, createdAt: now, updatedAt: now }; const transaction = db.transaction([OBJECTS_STORE, REVISIONS_STORE], "readwrite"); transaction.objectStore(OBJECTS_STORE).put({ ...object, revision: undefined }); transaction.objectStore(REVISIONS_STORE).put({ ...revision, key: revisionKey(id, 1) } satisfies StoredRevision<TPayload>); await transactionDone(transaction); db.close(); return object; }
export async function appendLocalObjectRevision<TPayload>(objectId: string, payload: TPayload, provenance: ScientificProvenance, artifacts?: ScientificArtifact[]): Promise<ScientificObjectRevision<TPayload>> { const db = await openDatabase(); const transaction = db.transaction([OBJECTS_STORE, REVISIONS_STORE], "readwrite"); const objectStore = transaction.objectStore(OBJECTS_STORE); const current = (await requestResult(objectStore.get(objectId))) as ScientificObject | undefined; if (!current) { transaction.abort(); db.close(); throw new Error("SCIENTIFIC_OBJECT_NOT_FOUND"); } const nextRevision = current.currentRevision + 1; const now = new Date().toISOString(); const revision: ScientificObjectRevision<TPayload> = { objectId, revision: nextRevision, payload, provenance, artifacts, createdAt: now }; objectStore.put({ ...current, currentRevision: nextRevision, updatedAt: now }); transaction.objectStore(REVISIONS_STORE).put({ ...revision, key: revisionKey(objectId, nextRevision) } satisfies StoredRevision<TPayload>); await transactionDone(transaction); db.close(); return revision; }
export async function getLocalScientificObject<TPayload = unknown>(id: string): Promise<ScientificObject<TPayload> | undefined> { const db = await openDatabase(); const transaction = db.transaction([OBJECTS_STORE, REVISIONS_STORE], "readonly"); const stored = (await requestResult(transaction.objectStore(OBJECTS_STORE).get(id))) as ScientificObject<TPayload> | undefined; if (!stored) { await transactionDone(transaction); db.close(); return undefined; } const storedRevision = (await requestResult(transaction.objectStore(REVISIONS_STORE).get(revisionKey(id, stored.currentRevision)))) as StoredRevision<TPayload> | undefined; await transactionDone(transaction); db.close(); if (!storedRevision) return stored; const { key: _key, ...revision } = storedRevision; return { ...stored, revision }; }
export async function listLocalScientificObjects<TPayload = unknown>(projectId: string): Promise<Array<ScientificObject<TPayload>>> { const db = await openDatabase(); const transaction = db.transaction(OBJECTS_STORE, "readonly"); const index = transaction.objectStore(OBJECTS_STORE).index("byProject"); const objects = (await requestResult(index.getAll(projectId))) as Array<ScientificObject<TPayload>>; await transactionDone(transaction); db.close(); return objects.sort((a, b) => (b.updatedAt || "").localeCompare(a.updatedAt || "")); }
export async function getLocalObjectRevision<TPayload = unknown>(objectId: string, revision: number): Promise<ScientificObjectRevision<TPayload> | undefined> { const db = await openDatabase(); const transaction = db.transaction(REVISIONS_STORE, "readonly"); const stored = (await requestResult(transaction.objectStore(REVISIONS_STORE).get(revisionKey(objectId, revision)))) as StoredRevision<TPayload> | undefined; await transactionDone(transaction); db.close(); if (!stored) return undefined; const { key: _key, ...result } = stored; return result; }
export async function createLocalScientificReference(input: { projectId: string; reference: ScientificObjectReference; containerObjectId?: string; role?: string; }): Promise<StoredScientificReference> { if (input.reference.projectId !== input.projectId) throw new Error("CROSS_PROJECT_REFERENCE_NOT_ALLOWED_V1"); const db = await openDatabase(); const stored: StoredScientificReference = { id: makeId(), projectId: input.projectId, containerObjectId: input.containerObjectId, role: input.role, reference: input.reference, createdAt: new Date().toISOString() }; const transaction = db.transaction(REFERENCES_STORE, "readwrite"); transaction.objectStore(REFERENCES_STORE).put(stored); await transactionDone(transaction); db.close(); return stored; }
export async function resolveLocalScientificReference<TPayload = unknown>(reference: ScientificObjectReference): Promise<ScientificObject<TPayload> | ScientificObjectRevision<TPayload> | undefined> { if (reference.mode === "frozen") return undefined; const object = await getLocalScientificObject<TPayload>(reference.objectId); if (!object) return undefined; if (reference.mode === "live") return object; if (reference.revision == null) return undefined; return await getLocalObjectRevision<TPayload>(reference.objectId, reference.revision); }
