# Generated by Django 5.1.6 on 2026-03-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_appversion_id_alter_article_id_alter_book_id_and_more'),
        ('laboratory', '0007_remove_laboratorymodule_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='mahsulot',
            name='project',
        ),
        migrations.RemoveField(
            model_name='softwareapp',
            name='project',
        ),
        migrations.RemoveField(
            model_name='course',
            name='project',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='project',
        ),
        migrations.RemoveField(
            model_name='article',
            name='project',
        ),
        migrations.RemoveField(
            model_name='category',
            name='project',
        ),
        migrations.RemoveField(
            model_name='book',
            name='project',
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='AppVersion',
        ),
        migrations.DeleteModel(
            name='Documentation',
        ),
        migrations.DeleteModel(
            name='Mahsulot',
        ),
        migrations.DeleteModel(
            name='SoftwareApp',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
